os: linux
language: scala
jdk: oraclejdk8
git:
  submodules: false
script:
  - git submodule init
  - git submodule update tests/scalapb
  - git clone --recursive --single-branch https://github.com/lampepfl/dotty.git
  - bin/gauge -o /dev/stdout -p bin/plan-ci 9999 master
