os: linux
language: scala
jdk: oraclejdk8
scala:
  - 2.12.4
git:
  submodules: false
branches:
  only:
    - master
    - develop
script:
  - git submodule init
  - git submodule update tests/scalapb
  - git clone --recursive --single-branch https://github.com/lampepfl/dotty.git
  - echo "hello, world" > /dev/stdout
  - bin/sync-profiles
  - bin/gauge -o data.csv -p profiles/ci.plan 9999 master
  - cat data.csv
  - mkdir data && bin/csv -p profiles/ci.yml data.csv data/
