os: linux
language: scala
jdk: oraclejdk8
scala:
  - 2.12.4
git:
  submodules: false
branches:
  only:
    - master
script:
  - git submodule init
  - git submodule update tests/scalapb
  - git clone --recursive --single-branch https://github.com/lampepfl/dotty.git
  - echo "hello, world" > /dev/stdout
  - bin/gauge -o /dev/stdout -p bin/plan-ci 9999 master
